#%RAML 1.0 Overlay
extends: walia-hospital.raml

title: ዋልያ ሆስፒታል 
documentation: 
 - title: መግቢያ
   content: ይሄ እንትን
 - title: ፔሸንትስ
   content: ስድልጅድስልፍፍንስድፍልስድንስድልጅድስልፍፍንስድፍልስድን

/patients:
  description: ይሄ ሪሶርስ የያዘውስልድልስድልስ ድ

 