#%RAML 1.0 NamedExample
[
                    {
                      "id": 1,
                      "name": "Amoxa",
                      "dosage": "2mg"
                    }
                  ,
                   {
                      "id": 2,
                      "name": "Paracetamol",
                      "dosage": "2mg"
                    }
              ]