#%RAML 1.0 NamedExample
 {
                    "patientID": "p01",
                    "name": "Abebe Kebede",
                    "email": "abebe@gmail.com",
                    "sex": "male",
                    "age": 22,
                    "address": {
                      "country": "Ethiopia",
                      "city": "Addis Ababa",
                      "street": "Bole"
                    },
                    "room_service": false
                  }