#%RAML 1.0 NamedExample
[
                  {
                    "patientID": "p01",
                    "name": "Abebech Kebede",
                    "email": "abebech@gmail.com",
                    "age": 22,
                    "sex": "female",
                    "address": {
                      "country": "Ethiopia",
                      "city": "Addis Ababa",
                      "street": "Bole"
                    },
                  "room_service":  false
                  
                  },
                  {
                    "patientID": "p01",
                    "name": "Chala Alemu",
                    "email": "chala@gmail.com",
                    "sex": "male",
                    "age": 22,
                    "address": {
                      "country": "Ethiopia",
                      "city": "Addis Ababa",
                      "street": "Bole"
                    },
                    "room_service": true
                  },
                  {
                    "patientID": "p01",
                    "name": "Abebe Kebede",
                    "email": "abebe@gmail.com",
                    "sex": "male",
                    "age": 22,
                    "address": {
                      "country": "Ethiopia",
                      "city": "Addis Ababa",
                      "street": "Bole"
                    },
                    "room_service": true
                  }

              ]