#%RAML 1.0 Trait

queryParameters:
  offset:
    description: The first entry in the table
    type: integer
    required: false
    default: 0
  limit:
    description: The number of entries
    type: integer
    required: false
    default: 10
  page:
    description: The returned pages
    type: integer
    required: false
  